---
# Initial, common, system setup steps

- name: reverse the enabling of sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: 'Defaults\s*!requiretty'
    replace: '^Defaults requiretty'
    backup: yes

- name: Remove repo file
  file:
    state: absent
    path: /etc/yum.repos.d/open_three-tier-app.repo

- name: remove base tools and three tier app packages
  package:
    name: "{{ package }}"
    state: absent
  loop:
    - httpie
    - python-pip
    - haproxy
    - tomcat
    - postgresql-server
  loop_control:
    loop_var: package


- name: Remove index.html
  file:
    state: absent
    path: /usr/share/tomcat/webapps/ROOT/index.html
