---
- name: In-Memory inventory playbook
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Fetch Instance Info
      os_server_info:
        cloud: openstack
      register: result

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.group }}"
      with_items: "{{result.openstack_servers}}"

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.deployment_name }}"
      with_items: "{{result.openstack_servers}}"
